version: '3'
services:
  php:
    container_name: ${APPLICATION_NAME}_php
    restart: always
    build:
      context: ./php
    depends_on:
      - mysql_database_host
    volumes:
      - "./php/conf.d/00-ioncube.ini:/usr/local/etc/php/conf.d/00-ioncube.ini"
      - "./php/conf.d/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini"
      - "./php/home/.bash_aliases:/root/.bash_aliases"
      - "./php/home/.bash_git:/root/.bash_git"
      - "./php/home/.bash_profile:/root/.bash_profile"
      - "./php/home/.bashrc:/root/.bashrc"
      - "./php/home/.git-completion.bash:/root/.git-completion.bash"
      - "./php/home/.git-prompt.sh:/root/.git-prompt.sh"
      - "./php/home/.vimrc:/root/.vimrc"
      - "${APPLICATION_PATH}:/var/www/html"
    ports:
      - "${APACHE_PORT}:80"
    environment:
      - MYSQL_BYPASS_HOSTNAME=mysql_database_host

  mysql_database_host:
    image: mysql:5.6
    container_name: ${APPLICATION_NAME}_mysql

    volumes:
      - ./mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ${MYSQL_INIT_FOLDER}:/docker-entrypoint-initdb.d/
      - ./mysql/data-${APPLICATION_NAME}:/var/lib/mysql:rw
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - MYSQL_DATABASE=docker_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APPLICATION_NAME}_phpmyadmin
    depends_on:
      - mysql_database_host
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_database_host
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "PHPMYADMIN_PORT:80"
